# Site settings
baseurl = "https://example.org/"
languageCode = "en-us"
title = "Tim Moor | Open Source Ninja"
theme = "hugo-freelancer-theme"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Tim Moor"
    description = "Open Source Ninja"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "webuimaker@email.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "Tim Moor"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "Tim Moor"
        subtitle = "Cloud Architect - Platform/Automation Specialist"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Experience"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Service"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        content = "Technical Evangelist, Propeller Head, Super Geek and Open Source Ninja are just some of the names I been called. I like to think these terms of endearment are used when someone is highly motivated, confident and passionate about their craft. The following resume will endeavor to demonstrate that I am a highly motivated, confident and conscientious individual with a proven track record of acheivement and success. I am looking to leverage the skills and experience of the last 10 years to solve enable success in your orgnaisation."

        [params.about.button]
            text = "Download CV"
            link = "#"
            icon = "download"
			
    [params.blog]
        title = "Blog"
        # The about text is splitted into a left and right column
        left = "Freelancer is a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional LESS stylesheets for easy customization."
        right = "Tim Whether you're a student looking to showcase your work, a professional looking to attract clients, or a graphic artist looking to share your projects, this template is the perfect starting point!"

        [params.blog.more]
            text = "More Blog"
            link = ""
            icon = "download"


    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Copyright &copy; Mobius Design Studio 2017"

        [params.footer.location]
            title = "Call Tim"
            # Postal address (add as many lines as necessary)
            address = ["022 1004707"]

        [params.footer.social]
            title = "Get Social"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-facebook"
                link = "#"

            [[params.footer.social.networks]]
                icon = "fa-google-plus"
                link=  "#"
            [[params.footer.social.networks]]
                icon = "fa-twitter"
                link=  "#"
            [[params.footer.social.networks]]
                icon = "fa-linkedin"
                link=  "#"
            [[params.footer.social.networks]]
                icon = "fa-github"
                link=  "#"

        [params.footer.credits]
            title = "Send an email"
            text = "tim.moor@linux-geek.co.nz"
            link = "mailto:tim.moor@linux-geek.co.nz"
			
